"""add_salon_settings

Revision ID: b1a41a676acb
Revises: b842e8a7c3c2
Create Date: 2026-07-17 11:49:45.400300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a41a676acb'
down_revision: Union[str, None] = 'b842e8a7c3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('owner_name', sa.String(length=200), nullable=True))
    op.add_column('salons', sa.Column('hours_open', sa.String(length=5), nullable=True))
    op.add_column('salons', sa.Column('hours_close', sa.String(length=5), nullable=True))
    op.add_column('salons', sa.Column('default_deposit_pct', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salons', 'default_deposit_pct')
    op.drop_column('salons', 'hours_close')
    op.drop_column('salons', 'hours_open')
    op.drop_column('salons', 'owner_name')
    # ### end Alembic commands ###
