"""add_inventory_suppliers

Revision ID: b842e8a7c3c2
Revises: 6bdf449c0713
Create Date: 2026-07-12 14:34:17.500553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b842e8a7c3c2'
down_revision: Union[str, None] = '6bdf449c0713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('length', sa.String(length=20), nullable=False),
    sa.Column('packs', sa.Integer(), nullable=False),
    sa.Column('max_packs', sa.Integer(), nullable=False),
    sa.Column('price_per_pack', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salon_id', 'color', 'length', name='uq_stock_color_length')
    )
    op.create_index('ix_stock_items_salon', 'stock_items', ['salon_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suppliers_salon', 'suppliers', ['salon_id'], unique=False)
    op.create_table('stock_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('stock_item_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_pack', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_purchases_salon_occurred', 'stock_purchases', ['salon_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_purchases_salon_occurred', table_name='stock_purchases')
    op.drop_table('stock_purchases')
    op.drop_index('ix_suppliers_salon', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_stock_items_salon', table_name='stock_items')
    op.drop_table('stock_items')
    # ### end Alembic commands ###
